language: python

python:
  - "2.7"

services:
  - postgresql

before_install:
  - export DATABASE_URL='postgresql://marlone911:@localhost/test_bev'
  - export FLASK_CONFIG="testing"
  - export SECRET_KEY="thisissecret"

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - sudo -u postgres createuser marlone911
  - psql -c 'create database test_bev;' -U postgres


script:
  - python manage.py test --coverage
  - nosetests --with-coverage --cover-package=app

after_script:
  - coveralls --config_file .coveragerc
