language: python

python:
  - "2.7"

services:
  - postgresql

before_install:
  - export DATABASE_URL='postgresql://marlone911@localhost/travis_ci_test'
  - export FLASK_CONFIG="testing"

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py db migrate
  - python manage.py db upgrade

script:
  - nosetests --with-coverage --cover-package=app

after_script:
  - coveralls
