language: python

python:
  - "2.7"

services:
  - postgresql

before_install:
  - export DATABASE_URL='postgresql://marlone911:bev@localhost:5432/newbev'

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - nosetests --with-coverage --cover-package=app

after_script:
  - coveralls
