"""empty message

Revision ID: 063d0415feb2
Revises: 99109143debb
Create Date: 2018-02-03 14:45:42.651219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063d0415feb2'
down_revision = '99109143debb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date_of_event', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'date_of_event')
    # ### end Alembic commands ###
