"""empty message

Revision ID: 5d4a6fa0a3bf
Revises: 872ef952ad0b
Create Date: 2018-04-18 10:18:24.002795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4a6fa0a3bf'
down_revision = '872ef952ad0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstName', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('lastName', sa.String(length=50), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('user', 'lastName')
    op.drop_column('user', 'firstName')
    # ### end Alembic commands ###
