"""empty message

Revision ID: 99109143debb
Revises: c78fbaec35bd
Create Date: 2018-02-03 13:38:53.970755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99109143debb'
down_revision = 'c78fbaec35bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('event', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('modified_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'modified_on')
    op.drop_column('event', 'created_on')
    op.drop_column('event', 'created_by')
    # ### end Alembic commands ###
